"Lists of strings to pick from pseudorandomly."


(setv meal-messages #(
  "Finally, some good pizza."
  "Macaroni with the chicken shtrips. Ugh!"
  "Mamma mia! That's a spicy meatball."
  "My, this is a yummy slime mold!"
  "Tastes like chicken."
  "You are revived with some hot soup."
  "You chow down on a good steak."
  "You eat some oatmeal, so you don't dry up."
  "You enjoy a refreshing salad."
  "You have a bagel (to absorb the poison)."
  "You tuck into some hearty roast vegetables."))

(setv snack-messages #(
  "French fries: bad for the heart, but good for the soul."
  #[[These Larmers™ brand ham medallions are delightful. No wonder they've been "America's Favorite Taste" since 1928.]]
  "You dine on cucumber sandwiches. Very classy."
  "You drink some magically carbonated soda."
  "You eat a whole bucket of popcorn. The movie hasn't even started yet."
  "You eat an apple. Core dumped."
  "You enjoy some curry puffs."
  "You have some mixed nuts. They're mostly peanuts."
  "You have some tortilla chips and salsa."))

(setv dessert-messages #(
  #[["C" is for "cookie". That's good enough for me.]]
  "That beautiful cinnamon roll was too good for this world."
  "You eat a slice of birthday cake. Whose birthday is it?"
  "You eat some funnel cake. How festive."
  "You have some chocolate babka, just like Bubbe used to make."
  "You have some peppermint-stick ice cream. My favorite!"
  "You have some refreshing lemon sorbet."
  "You scarf down some brownies."))

(setv rotten-food-messages #(
  "I think you misread the expiration date on those cookies."
  "Maybe you shouldn't have gone with the steak tartare."
  "Rotten meat! Kids, you gotta keep your meat ice-cold."
  "Spoiled milk was a bad choice."
  "This kobold corpse tastes terrible!"
  "This peach is subpar."
  "This wall chicken is unsanitary."
  "You eat a century egg, but you don't enjoy it."
  "You eat a poison apple. Hey, that was for a different princess."
  "You eat some blue cheese. Blue cheese has mold in it."))

(setv wand-of-nothing-messages #(
  "ACHIEVEMENT UNLOCKED: Nothing"
  "All your hair suddenly falls out."
  "BARF!"
  "Everything looks SO boring now."
  "Goblin mode on."
  "God mode enabled."
  "It constricts your throat!"
  "Morgoth, Lord of Darkness laughs off the attack."
  "Spots appear before your eyes."
  "The Dreaming God has awakened."
  "The wand asks you to rate your customer-service experience. You prefer not to answer."
  "The wand beeps loudly."
  "The wand crumbles to dust."
  "The wand detonates in a massive but purely cosmetic explosion."
  "The wand fires a burst of confetti."
  "The wand fires a powerful plasma blast aimed at nothing in particular."
  "The wand needs a software update to continue, but the servers for that are long gone."
  "The wand plays a tinny recording of an error message in French."
  "The wand plays an ad for a bad smartphone game."
  "The wand says some tobacco words."
  "The wand squirts water in your face."
  "The wand starts reciting the Navy SEALs copypasta. You sigh and throw it away."
  "The wand turns into a chinchilla and scampers away."
  "The wand turns into a limp strand of spaghetti."
  "The wand turns itself into a pickle! Funniest stuff you've ever seen."
  "Updated my journal."
  "What a horrible night to have a curse."
  "You are suddenly very masculine!"
  "You briefly hallucinate a three-headed monkey."
  "You found kitten!"
  "You gain 15 science points."
  "You gain 500 XP. Level up!"
  "You have a normal feeling for a moment, then it passes."
  "You have a strange feeling for a moment, then it passes."
  "You have a strange thought about Vaporeon."
  "You miss Geralt."
  "You smell something familiar."
  "You sneeze."
  "You suddenly think of a great recipe for muffins."
  "You suddenly yearn for your distant homeland."
  "You summon a butterfly. It flies away."
  "You've got mail."
  "Your dad turns into a chickenrat."
  "Your skin turns orange."
  "python3: segmentation fault (core dumped)"
  #[[The wand asks "For what do you wish?" After you reply, it says "Yeah, me too."]]
  #[[The wand says "I've not seen such bravery!".]]
  #[[The wand says "Moof!".]]
  #[[The wand says "Prince Argonn, you are about to die."]]))

(setv death-messages #(
  "A blamed pity."
  "Ain't that a bite!"
  "Aw, fiddlesticks."
  "Better you than me."
  "Epic fail!"
  "Game over, man."
  "How annoying."
  "Idok must be very proud of himself."
  "I hate it when that happens."
  "Miz!"
  "Nebekh!"
  "Oh, I'm sorry!"
  "Or as I like to call it, executed a full-scale divestment from the corporeal sphere."
  "Press F to pay respects."
  "RIP in pepperoni."
  "Sadder than a map!"
  "Sad trombone."
  "Shazbot!"
  "Sic semper adventurerus."
  "That'll leave a mark."
  "That's a shame."
  "The agony of defeat!"
  "The monsters dab in victory."
  "This may be problematic for your quest."
  "This should make for quite an obituary."
  "Thus the way of all flesh."
  "Tough darts."
  "Très bummer."
  "TS."
  "Wasted!"
  "Well, that's how the cookie crumbles."
  "What a way to go."
  "Whoops."
  "You're in a bad loaf now."
  "You were too good for this world, too pure."))
